name: deepacoustic
channels:
  - defaults
dependencies:
  - ca-certificates=2019.11.27
  - certifi=2018.8.24
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.0.2u
  - pip=10.0.1
  - python=3.5.6
  - readline=7.0
  - setuptools=40.2.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - audioread==2.1.8
    - bleach==1.5.0
    - cffi==1.13.2
    - decorator==4.4.1
    - enum34==1.1.6
    - gast==0.3.3
    - grpcio==1.26.0
    - h5py==2.10.0
    - html5lib==0.9999999
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - librosa==0.6.2
    - llvmlite==0.31.0
    - markdown==3.1.1
    - numba==0.47.0
    - numpy==1.18.1
    - protobuf==3.11.2
    - pycparser==2.19
    - resampy==0.2.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - six==1.14.0
    - soundfile==0.10.2
    - tensorboard==1.12.2
    - tensorflow==1.12.0
    - tensorflow-tensorboard==0.4.0
    - termcolor==1.1.0
    - werkzeug==0.16.1

